--S1
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

--S2
BEGIN TRANSACTION ISOLATION LEVEL READ COMMITTED;

--S1
SELECT SUM(rating) FROM pizzeria;

--S2
INSERT INTO pizzeria (id, name, rating) VALUES (10, 'Kazan Pizza', 5);
COMMIT;

--S1
SELECT SUM(rating) FROM pizzeria;
COMMIT;
SELECT SUM(rating) FROM pizzeria;


--S2
SELECT SUM(rating) FROM pizzeria;